spring:
  # 데이터베이스 접속정보 설정
  datasource:
    username: root
    password: 1234
    url: jdbc:mariadb://localhost:3306/profile
    driver-class-name: org.mariadb.jdbc.Driver
  # 타임리프 설정
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
  
mybatis:
  mapper-locations:
  - classpath:config/mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true